        !COMPILER-GENERATED INTERFACE MODULE: Thu Sep 29 20:18:04 2016
        MODULE ADJUSTFERMILEVEL__genmod
          INTERFACE 
            SUBROUTINE ADJUSTFERMILEVEL
              USE VMCPLACE
            END SUBROUTINE ADJUSTFERMILEVEL
          END INTERFACE 
        END MODULE ADJUSTFERMILEVEL__genmod
