        !COMPILER-GENERATED INTERFACE MODULE: Thu Sep 29 20:18:05 2016
        MODULE BDG_BAND__genmod
          INTERFACE 
            SUBROUTINE BDG_BAND(UNITCELL)
              USE CRYSTAL
              TYPE (UNITCELLCONFIG) ,TARGET :: UNITCELL
            END SUBROUTINE BDG_BAND
          END INTERFACE 
        END MODULE BDG_BAND__genmod
