        !COMPILER-GENERATED INTERFACE MODULE: Thu Sep 29 13:27:01 2016
        MODULE BISEC_OPT__genmod
          INTERFACE 
            SUBROUTINE BISEC_OPT
            END SUBROUTINE BISEC_OPT
          END INTERFACE 
        END MODULE BISEC_OPT__genmod
