        !COMPILER-GENERATED INTERFACE MODULE: Wed Sep 28 19:05:03 2016
        MODULE CHECKDYSON__genmod
          INTERFACE 
            SUBROUTINE CHECKDYSON(N)
              INTEGER(KIND=4) :: N
            END SUBROUTINE CHECKDYSON
          END INTERFACE 
        END MODULE CHECKDYSON__genmod
