        !COMPILER-GENERATED INTERFACE MODULE: Thu Sep 29 13:27:03 2016
        MODULE COBYLA_OPT__genmod
          INTERFACE 
            SUBROUTINE COBYLA_OPT
            END SUBROUTINE COBYLA_OPT
          END INTERFACE 
        END MODULE COBYLA_OPT__genmod
