        !COMPILER-GENERATED INTERFACE MODULE: Thu Sep 29 20:18:05 2016
        MODULE CONJUGATE_SEARCH__genmod
          INTERFACE 
            SUBROUTINE CONJUGATE_SEARCH(DVAR,JSEED)
              USE VMCPLACE
              REAL(KIND=8) :: DVAR(NVAR)
              INTEGER(KIND=4) :: JSEED
            END SUBROUTINE CONJUGATE_SEARCH
          END INTERFACE 
        END MODULE CONJUGATE_SEARCH__genmod
