        !COMPILER-GENERATED INTERFACE MODULE: Thu Sep 29 20:18:06 2016
        MODULE COORDINATION__genmod
          INTERFACE 
            SUBROUTINE COORDINATION
              USE VMCPLACE
            END SUBROUTINE COORDINATION
          END INTERFACE 
        END MODULE COORDINATION__genmod
