        !COMPILER-GENERATED INTERFACE MODULE: Thu Sep 29 13:27:03 2016
        MODULE DEFINEJOB__genmod
          INTERFACE 
            SUBROUTINE DEFINEJOB
            END SUBROUTINE DEFINEJOB
          END INTERFACE 
        END MODULE DEFINEJOB__genmod
