        !COMPILER-GENERATED INTERFACE MODULE: Thu Sep 29 13:27:04 2016
        MODULE DLOGPENALTY__genmod
          INTERFACE 
            SUBROUTINE DLOGPENALTY
            END SUBROUTINE DLOGPENALTY
          END INTERFACE 
        END MODULE DLOGPENALTY__genmod
