        !COMPILER-GENERATED INTERFACE MODULE: Wed Sep 28 19:05:05 2016
        MODULE DOUBLONHOLON__genmod
          INTERFACE 
            FUNCTION DOUBLONHOLON(CHI,CHJ)
              INTEGER(KIND=4) :: CHI
              INTEGER(KIND=4) :: CHJ
              INTEGER(KIND=4) :: DOUBLONHOLON
            END FUNCTION DOUBLONHOLON
          END INTERFACE 
        END MODULE DOUBLONHOLON__genmod
