        !COMPILER-GENERATED INTERFACE MODULE: Wed Sep 28 19:05:05 2016
        MODULE EXCHANGE__genmod
          INTERFACE 
            SUBROUTINE EXCHANGE(I,J)
              INTEGER(KIND=4) :: I
              INTEGER(KIND=4) :: J
            END SUBROUTINE EXCHANGE
          END INTERFACE 
        END MODULE EXCHANGE__genmod
