        !COMPILER-GENERATED INTERFACE MODULE: Thu Sep 29 20:18:06 2016
        MODULE HEXKONDO__genmod
          INTERFACE 
            SUBROUTINE HEXKONDO
            END SUBROUTINE HEXKONDO
          END INTERFACE 
        END MODULE HEXKONDO__genmod
