        !COMPILER-GENERATED INTERFACE MODULE: Thu Sep 29 20:18:06 2016
        MODULE HONEYCOMB__genmod
          INTERFACE 
            SUBROUTINE HONEYCOMB
            END SUBROUTINE HONEYCOMB
          END INTERFACE 
        END MODULE HONEYCOMB__genmod
