        !COMPILER-GENERATED INTERFACE MODULE: Wed Sep 28 19:05:05 2016
        MODULE INACTIVE__genmod
          INTERFACE 
            FUNCTION INACTIVE(X)
              REAL(KIND=8) :: X
              LOGICAL(KIND=4) :: INACTIVE
            END FUNCTION INACTIVE
          END INTERFACE 
        END MODULE INACTIVE__genmod
