        !COMPILER-GENERATED INTERFACE MODULE: Thu Sep 29 20:18:06 2016
        MODULE INCLUDENN__genmod
          INTERFACE 
            SUBROUTINE INCLUDENN
              USE VMCPLACE
            END SUBROUTINE INCLUDENN
          END INTERFACE 
        END MODULE INCLUDENN__genmod
