        !COMPILER-GENERATED INTERFACE MODULE: Thu Sep 29 13:27:01 2016
        MODULE INFRASTRUCTURE__genmod
          INTERFACE 
            SUBROUTINE INFRASTRUCTURE
            END SUBROUTINE INFRASTRUCTURE
          END INTERFACE 
        END MODULE INFRASTRUCTURE__genmod
