        !COMPILER-GENERATED INTERFACE MODULE: Thu Sep 29 13:27:01 2016
        MODULE INITCONFIG__genmod
          INTERFACE 
            SUBROUTINE INITCONFIG
            END SUBROUTINE INITCONFIG
          END INTERFACE 
        END MODULE INITCONFIG__genmod
