        !COMPILER-GENERATED INTERFACE MODULE: Thu Sep 29 20:18:04 2016
        MODULE KAGOME2X2__genmod
          INTERFACE 
            SUBROUTINE KAGOME2X2
            END SUBROUTINE KAGOME2X2
          END INTERFACE 
        END MODULE KAGOME2X2__genmod
