        !COMPILER-GENERATED INTERFACE MODULE: Thu Sep 29 20:18:04 2016
        MODULE KAGOME__genmod
          INTERFACE 
            SUBROUTINE KAGOME
            END SUBROUTINE KAGOME
          END INTERFACE 
        END MODULE KAGOME__genmod
