        !COMPILER-GENERATED INTERFACE MODULE: Thu Sep 29 20:18:04 2016
        MODULE KAGOMEJ__genmod
          INTERFACE 
            SUBROUTINE KAGOMEJ
            END SUBROUTINE KAGOMEJ
          END INTERFACE 
        END MODULE KAGOMEJ__genmod
