        !COMPILER-GENERATED INTERFACE MODULE: Thu Sep 29 13:27:04 2016
        MODULE LEFT_DLOGPENALTY__genmod
          INTERFACE 
            SUBROUTINE LEFT_DLOGPENALTY(IA,JA,INFO)
              INTEGER(KIND=4) :: IA
              INTEGER(KIND=4) :: JA
              INTEGER(KIND=4) :: INFO
            END SUBROUTINE LEFT_DLOGPENALTY
          END INTERFACE 
        END MODULE LEFT_DLOGPENALTY__genmod
