        !COMPILER-GENERATED INTERFACE MODULE: Thu Sep 29 20:18:05 2016
        MODULE LMOPTIMIZER__genmod
          INTERFACE 
            SUBROUTINE LMOPTIMIZER
            END SUBROUTINE LMOPTIMIZER
          END INTERFACE 
        END MODULE LMOPTIMIZER__genmod
