        !COMPILER-GENERATED INTERFACE MODULE: Thu Sep 29 20:18:05 2016
        MODULE MAKETABLES__genmod
          INTERFACE 
            SUBROUTINE MAKETABLES
              USE VMCPLACE
            END SUBROUTINE MAKETABLES
          END INTERFACE 
        END MODULE MAKETABLES__genmod
