        !COMPILER-GENERATED INTERFACE MODULE: Thu Sep 29 13:27:02 2016
        MODULE MCTHREAD__genmod
          INTERFACE 
            SUBROUTINE MCTHREAD
            END SUBROUTINE MCTHREAD
          END INTERFACE 
        END MODULE MCTHREAD__genmod
