        !COMPILER-GENERATED INTERFACE MODULE: Thu Sep 29 13:27:00 2016
        MODULE MEASURE__genmod
          INTERFACE 
            SUBROUTINE MEASURE
            END SUBROUTINE MEASURE
          END INTERFACE 
        END MODULE MEASURE__genmod
