        !COMPILER-GENERATED INTERFACE MODULE: Thu Sep 29 13:27:04 2016
        MODULE MFT2VMC__genmod
          INTERFACE 
            SUBROUTINE MFT2VMC
            END SUBROUTINE MFT2VMC
          END INTERFACE 
        END MODULE MFT2VMC__genmod
