        !COMPILER-GENERATED INTERFACE MODULE: Wed Sep 28 19:05:05 2016
        MODULE MILISECOND__genmod
          INTERFACE 
            FUNCTION MILISECOND
              INTEGER(KIND=4) :: MILISECOND
            END FUNCTION MILISECOND
          END INTERFACE 
        END MODULE MILISECOND__genmod
