        !COMPILER-GENERATED INTERFACE MODULE: Thu Sep 29 12:53:57 2016
        MODULE MPI_AVERAGE__genmod
          INTERFACE 
            SUBROUTINE MPI_AVERAGE
            END SUBROUTINE MPI_AVERAGE
          END INTERFACE 
        END MODULE MPI_AVERAGE__genmod
