        !COMPILER-GENERATED INTERFACE MODULE: Thu Sep 29 20:18:06 2016
        MODULE NEIGHBORS__genmod
          INTERFACE 
            SUBROUTINE NEIGHBORS(UNITCELL)
              USE CRYSTAL
              TYPE (UNITCELLCONFIG) ,TARGET :: UNITCELL
            END SUBROUTINE NEIGHBORS
          END INTERFACE 
        END MODULE NEIGHBORS__genmod
