        !COMPILER-GENERATED INTERFACE MODULE: Thu Sep 29 20:18:05 2016
        MODULE NORMAL_BAND__genmod
          INTERFACE 
            SUBROUTINE NORMAL_BAND(UNITCELL)
              USE CRYSTAL
              TYPE (UNITCELLCONFIG) ,TARGET :: UNITCELL
            END SUBROUTINE NORMAL_BAND
          END INTERFACE 
        END MODULE NORMAL_BAND__genmod
