        !COMPILER-GENERATED INTERFACE MODULE: Thu Sep 29 20:18:04 2016
        MODULE OPTIMIZED_VAR__genmod
          INTERFACE 
            SUBROUTINE OPTIMIZED_VAR
            END SUBROUTINE OPTIMIZED_VAR
          END INTERFACE 
        END MODULE OPTIMIZED_VAR__genmod
