        !COMPILER-GENERATED INTERFACE MODULE: Wed Sep 28 19:05:05 2016
        MODULE PAIREXCHANGEABLE__genmod
          INTERFACE 
            FUNCTION PAIREXCHANGEABLE(SI,SJ)
              INTEGER(KIND=4) :: SI(2)
              INTEGER(KIND=4) :: SJ(2)
              LOGICAL(KIND=4) :: PAIREXCHANGEABLE
            END FUNCTION PAIREXCHANGEABLE
          END INTERFACE 
        END MODULE PAIREXCHANGEABLE__genmod
