        !COMPILER-GENERATED INTERFACE MODULE: Thu Sep 29 20:18:04 2016
        MODULE R2XR2_MANNUAL__genmod
          INTERFACE 
            SUBROUTINE R2XR2_MANNUAL
            END SUBROUTINE R2XR2_MANNUAL
          END INTERFACE 
        END MODULE R2XR2_MANNUAL__genmod
