        !COMPILER-GENERATED INTERFACE MODULE: Thu Sep 29 20:18:03 2016
        MODULE R2XR2KONDO__genmod
          INTERFACE 
            SUBROUTINE R2XR2KONDO
            END SUBROUTINE R2XR2KONDO
          END INTERFACE 
        END MODULE R2XR2KONDO__genmod
