        !COMPILER-GENERATED INTERFACE MODULE: Thu Sep 29 20:18:04 2016
        MODULE R2XR2_IONIC__genmod
          INTERFACE 
            SUBROUTINE R2XR2_IONIC
            END SUBROUTINE R2XR2_IONIC
          END INTERFACE 
        END MODULE R2XR2_IONIC__genmod
