        !COMPILER-GENERATED INTERFACE MODULE: Wed Sep 28 19:05:05 2016
        MODULE ROTATE120__genmod
          INTERFACE 
            SUBROUTINE ROTATE120(R)
              REAL(KIND=8) :: R(2)
            END SUBROUTINE ROTATE120
          END INTERFACE 
        END MODULE ROTATE120__genmod
