        !COMPILER-GENERATED INTERFACE MODULE: Wed Sep 28 19:05:05 2016
        MODULE ROTATE90__genmod
          INTERFACE 
            SUBROUTINE ROTATE90(R)
              REAL(KIND=8) :: R(2)
            END SUBROUTINE ROTATE90
          END INTERFACE 
        END MODULE ROTATE90__genmod
