        !COMPILER-GENERATED INTERFACE MODULE: Wed Sep 28 19:05:05 2016
        MODULE SUPEREXCHANGEABLE__genmod
          INTERFACE 
            FUNCTION SUPEREXCHANGEABLE(SI,SJ)
              INTEGER(KIND=4) :: SI(2)
              INTEGER(KIND=4) :: SJ(2)
              LOGICAL(KIND=4) :: SUPEREXCHANGEABLE
            END FUNCTION SUPEREXCHANGEABLE
          END INTERFACE 
        END MODULE SUPEREXCHANGEABLE__genmod
