        !COMPILER-GENERATED INTERFACE MODULE: Thu Sep 29 13:27:04 2016
        MODULE SUPEREXCHANGE__genmod
          INTERFACE 
            SUBROUTINE SUPEREXCHANGE(IA,JA,MODE)
              USE VMCPLACE
              INTEGER(KIND=4) :: IA
              INTEGER(KIND=4) :: JA
              CHARACTER(LEN=10) :: MODE
            END SUBROUTINE SUPEREXCHANGE
          END INTERFACE 
        END MODULE SUPEREXCHANGE__genmod
