        !COMPILER-GENERATED INTERFACE MODULE: Wed Sep 28 19:05:05 2016
        MODULE TYPEWRITER2COORD__genmod
          INTERFACE 
            SUBROUTINE TYPEWRITER2COORD(I,NDIM,LIMITS,COORD)
              INTEGER(KIND=4) :: NDIM
              INTEGER(KIND=4) :: I
              INTEGER(KIND=4) :: LIMITS(NDIM)
              INTEGER(KIND=4) :: COORD(NDIM)
            END SUBROUTINE TYPEWRITER2COORD
          END INTERFACE 
        END MODULE TYPEWRITER2COORD__genmod
