        !COMPILER-GENERATED INTERFACE MODULE: Wed Sep 28 19:05:05 2016
        MODULE TYPEWRITER__genmod
          INTERFACE 
            FUNCTION TYPEWRITER(NDIM,LIMITS,COORD)
              INTEGER(KIND=4) :: NDIM
              INTEGER(KIND=4) :: LIMITS(NDIM)
              INTEGER(KIND=4) :: COORD(NDIM)
              INTEGER(KIND=4) :: TYPEWRITER
            END FUNCTION TYPEWRITER
          END INTERFACE 
        END MODULE TYPEWRITER__genmod
