        !COMPILER-GENERATED INTERFACE MODULE: Thu Sep 29 13:27:04 2016
        MODULE UPDATEBOND__genmod
          INTERFACE 
            SUBROUTINE UPDATEBOND(MODE)
              USE VMCPLACE
              CHARACTER(LEN=10) :: MODE
            END SUBROUTINE UPDATEBOND
          END INTERFACE 
        END MODULE UPDATEBOND__genmod
