        !COMPILER-GENERATED INTERFACE MODULE: Thu Sep 29 13:27:04 2016
        MODULE UPDATEONSITE__genmod
          INTERFACE 
            SUBROUTINE UPDATEONSITE(MODE)
              CHARACTER(LEN=10) :: MODE
            END SUBROUTINE UPDATEONSITE
          END INTERFACE 
        END MODULE UPDATEONSITE__genmod
