        !COMPILER-GENERATED INTERFACE MODULE: Thu Sep 29 20:18:07 2016
        MODULE YRZ__genmod
          INTERFACE 
            SUBROUTINE YRZ
            END SUBROUTINE YRZ
          END INTERFACE 
        END MODULE YRZ__genmod
