        !COMPILER-GENERATED INTERFACE MODULE: Thu Sep 29 13:55:19 2016
        MODULE FILE2ARR__genmod
          INTERFACE 
            SUBROUTINE FILE2ARR(FILEFULLNAME,INFOARRAY)
              USE MYDATA
              CHARACTER(LEN=80) :: FILEFULLNAME
              TYPE (LINE_INFO) ,ALLOCATABLE :: INFOARRAY(:)
            END SUBROUTINE FILE2ARR
          END INTERFACE 
        END MODULE FILE2ARR__genmod
